"""add combined_tables to reservations

Revision ID: 8d2bc36fcebf
Revises: 7a51306548fd
Create Date: 2026-03-14 14:10:00.001259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d2bc36fcebf'
down_revision: Union[str, None] = '7a51306548fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
